// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBalURqUzmEURFVvUcvCukiP4wbFYC0aMc',
    appId: '1:741418873814:web:b1f32a1d1b059998976a77',
    messagingSenderId: '741418873814',
    projectId: 'fulfillkaro',
    authDomain: 'fulfillkaro.firebaseapp.com',
    storageBucket: 'fulfillkaro.appspot.com',
    measurementId: 'G-3XJZ4G73ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADmfU2NqVT6q15ld10ZW63uxdrg8VVto',
    appId: '1:741418873814:android:6552f39c192dd061976a77',
    messagingSenderId: '741418873814',
    projectId: 'fulfillkaro',
    storageBucket: 'fulfillkaro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTXGsx7Cd_tOFLUf9zVwuEWGqpbed-Kh4',
    appId: '1:741418873814:ios:90e1d6a5df8fe02b976a77',
    messagingSenderId: '741418873814',
    projectId: 'fulfillkaro',
    storageBucket: 'fulfillkaro.appspot.com',
    iosClientId: '741418873814-33j06vqnqvqtqotr626bm16un4u174e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fulfillKaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTXGsx7Cd_tOFLUf9zVwuEWGqpbed-Kh4',
    appId: '1:741418873814:ios:90e1d6a5df8fe02b976a77',
    messagingSenderId: '741418873814',
    projectId: 'fulfillkaro',
    storageBucket: 'fulfillkaro.appspot.com',
    iosClientId: '741418873814-33j06vqnqvqtqotr626bm16un4u174e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fulfillKaro',
  );
}
